#!/bin/env ruby
# encoding: utf-8

require 'nokogiri'
require 'geocoder'
require 'open-uri'
require 'mechanize'

class Iso


  address = 'Yeni Mecidiye Mh., 3009. Sokak, 35930 Alaçatı/Izmir Province, Turkey'

  loc = Geocoder.search(address).first

  prep = 'https://maps.google.com/maps?q=airport+near+' << loc.address_components[4]['long_name'] << '+' << loc.country
  key = "airport"

  @uno = []
  a = Mechanize.new
  page = a.get(prep)
  gsForm = page.forms[0]
  gsForm.encoding = 'utf-8'
  gForm = gsForm.submit
  gDoc = gForm.parser
  data = gDoc.css('script').text.to_s[64..-4][0..-14]
  parsed = eval(data)[:overlays][:markers]
  parsed.each do |node|
    prep = node[:latlng][:lat].to_s << ','
    prep << node[:latlng][:lng].to_s
    @uno << prep
  end
  @uno.each do |data|
    @set = []
    coded = Geocoder.search(data)
    coded.each do |d|
      if d.types.include?(key)
        @set << d
      end
    end
  end


end

