#!/bin/env ruby
#encoding: utf-8

require 'open-uri'
require 'nokogiri'
require 'json'
require 'mechanize'
require 'execjs'

a = Mechanize.new
page = a.get('https://maps.google.com/maps?q=hospitals+near+Dalyan Mh.,+4148.+Sokak,+35930 Çeşme/Izmir+Province,+Turkey')


gsForm = page.forms[0]
gsForm.encoding = 'utf-8'
gForm = gsForm.submit
gDoc = gForm.parser
data = gDoc.css('script').text.to_s[64..-4][0..-14]


puts data



#@parsed = eval(data)[:overlays][:markers]
#@parsed.each do |node|
#  duo = node[:id].to_s << ' '
#  duo << node[:latlng][:lat].to_s << ' '
#  duo << node[:latlng][:lng].to_s
#  puts duo
#end

<h3>Airports</h3>
    <ul>
        <% @location.air.each do |duo|%>
          <li><%= link_to duo.address, @location %></li>
<% end %>
    </ul>

<h3>Hospital</h3>
<ul>
<% @location.hosp.each do |duo|%>
      <li><%= link_to duo.address, @location %></li>
  <% end %>
</ul>
<h3>Bus Stops</h3>
<ul>
  <% @location.bus.each do |duo|%>

      <li><%= link_to duo.address, @location %></li>

  <% end %>
</ul>
<h3>Restaurants</h3>
<ul>
  <% @location.restaurant.each do |duo|%>
      <li><%= link_to duo.address, @location %></li>
<% end %>
</ul>








#JSON.parse(jData)['overlays']['markers'].each do |node|
#  puts node['id']
#  puts node['latlng']['lat']
#  puts node['latlng']['lng']
#  puts ''
#end








